version: "3"
volumes:
  node_modules:
  build:
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    restart: always
    environment:
      - MIX_ENV=docker
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
